/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaoyi_sujin_glstitch_StitchJNIWrapper */

#ifndef _Included_com_xiaoyi_sujin_glstitch_StitchJNIWrapper
#define _Included_com_xiaoyi_sujin_glstitch_StitchJNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
#undef com_xiaoyi_sujin_glstitch_StitchJNIWrapper_ORIENTATION_NONE
#define com_xiaoyi_sujin_glstitch_StitchJNIWrapper_ORIENTATION_NONE -1L
#undef com_xiaoyi_sujin_glstitch_StitchJNIWrapper_ORIENTATION_STD
#define com_xiaoyi_sujin_glstitch_StitchJNIWrapper_ORIENTATION_STD 0L
#undef com_xiaoyi_sujin_glstitch_StitchJNIWrapper_ORIENTATION_STD_MIRRORED
#define com_xiaoyi_sujin_glstitch_StitchJNIWrapper_ORIENTATION_STD_MIRRORED 1L
#undef com_xiaoyi_sujin_glstitch_StitchJNIWrapper_ORIENTATION_FLIPPED
#define com_xiaoyi_sujin_glstitch_StitchJNIWrapper_ORIENTATION_FLIPPED 2L
#undef com_xiaoyi_sujin_glstitch_StitchJNIWrapper_ORIENTATION_FLIPPED_MIRRORED
#define com_xiaoyi_sujin_glstitch_StitchJNIWrapper_ORIENTATION_FLIPPED_MIRRORED 3L
#undef com_xiaoyi_sujin_glstitch_StitchJNIWrapper_ORIENTATION_DIAGONAL
#define com_xiaoyi_sujin_glstitch_StitchJNIWrapper_ORIENTATION_DIAGONAL 4L
#undef com_xiaoyi_sujin_glstitch_StitchJNIWrapper_RENDER_DISP_MODE_INPUT
#define com_xiaoyi_sujin_glstitch_StitchJNIWrapper_RENDER_DISP_MODE_INPUT 0L
#undef com_xiaoyi_sujin_glstitch_StitchJNIWrapper_RENDER_DISP_MODE_OUTPUT
#define com_xiaoyi_sujin_glstitch_StitchJNIWrapper_RENDER_DISP_MODE_OUTPUT 1L
/*
 * Class:     com_xiaoyi_sujin_glstitch_StitchJNIWrapper
 * Method:    getOutputFrameW
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xiaoyi_sujin_glstitch_StitchJNIWrapper_getOutputFrameW
  (JNIEnv *, jobject);

/*
 * Class:     com_xiaoyi_sujin_glstitch_StitchJNIWrapper
 * Method:    getOutputFrameH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xiaoyi_sujin_glstitch_StitchJNIWrapper_getOutputFrameH
  (JNIEnv *, jobject);

/*
 * Class:     com_xiaoyi_sujin_glstitch_StitchJNIWrapper
 * Method:    init
 * Signature: (ZZZ)V
 */
JNIEXPORT void JNICALL Java_com_xiaoyi_sujin_glstitch_StitchJNIWrapper_init
  (JNIEnv *, jobject, jboolean, jboolean, jboolean);

/*
 * Class:     com_xiaoyi_sujin_glstitch_StitchJNIWrapper
 * Method:    prepare
 * Signature: (IIZ)V
 */
JNIEXPORT void JNICALL Java_com_xiaoyi_sujin_glstitch_StitchJNIWrapper_prepare
  (JNIEnv *, jobject, jint, jint, jboolean);

/*
 * Class:     com_xiaoyi_sujin_glstitch_StitchJNIWrapper
 * Method:    setRenderDisp
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_xiaoyi_sujin_glstitch_StitchJNIWrapper_setRenderDisp
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_xiaoyi_sujin_glstitch_StitchJNIWrapper
 * Method:    setRenderDispShowMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_xiaoyi_sujin_glstitch_StitchJNIWrapper_setRenderDispShowMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_xiaoyi_sujin_glstitch_StitchJNIWrapper
 * Method:    cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xiaoyi_sujin_glstitch_StitchJNIWrapper_cleanup
  (JNIEnv *, jobject);

/*
 * Class:     com_xiaoyi_sujin_glstitch_StitchJNIWrapper
 * Method:    setInputPixels
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_xiaoyi_sujin_glstitch_StitchJNIWrapper_setInputPixels
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_xiaoyi_sujin_glstitch_StitchJNIWrapper
 * Method:    setInputTexture
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_xiaoyi_sujin_glstitch_StitchJNIWrapper_setInputTexture
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_xiaoyi_sujin_glstitch_StitchJNIWrapper
 * Method:    process
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xiaoyi_sujin_glstitch_StitchJNIWrapper_process
  (JNIEnv *, jobject);

/*
 * Class:     com_xiaoyi_sujin_glstitch_StitchJNIWrapper
 * Method:    renderOutput
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xiaoyi_sujin_glstitch_StitchJNIWrapper_renderOutput
  (JNIEnv *, jobject);

/*
 * Class:     com_xiaoyi_sujin_glstitch_StitchJNIWrapper
 * Method:    getOutputPixels
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_xiaoyi_sujin_glstitch_StitchJNIWrapper_getOutputPixels
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
